let suggestion=[
    "Reliance Industries",
    "Tata Consultancy Services (TCS)",
    "HDFC Bank",
    "Hindustan Unilever (HUL)",
    "ICICI Bank",
    "Housing Development Finance Corporation Limited (HDFC)",
    "State Bank of India (SBI)",
    "Bajaj Finance",
    "Kotak Mahindra Bank",
    "Bajaj",
    "Muthoot",
    "Adani",
    "Hindustan Petroleum",
    "Maruti Suzuki",
    "Mahindra & Mahindra",
];